"""change child_age to child_dob in admission_inquiries

Revision ID: 393f8bee3535
Revises: bba366ce6c2c
Create Date: 2026-05-22 07:54:45.986966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393f8bee3535'
down_revision: Union[str, None] = 'bba366ce6c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_inquiries', sa.Column('child_dob', sa.String(length=20), nullable=True, comment='[PII] ISO date e.g. 2018-04-12'))
    op.drop_column('admission_inquiries', 'child_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_inquiries', sa.Column('child_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('admission_inquiries', 'child_dob')
    # ### end Alembic commands ###
