"""create admission and contact tables

Revision ID: bba366ce6c2c
Revises: 
Create Date: 2026-05-18 11:29:22.336253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba366ce6c2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_name', sa.String(length=100), nullable=False),
    sa.Column('guardian_email', sa.String(length=255), nullable=False),
    sa.Column('guardian_phone', sa.String(length=20), nullable=False),
    sa.Column('child_name', sa.String(length=100), nullable=False),
    sa.Column('child_age', sa.Integer(), nullable=False),
    sa.Column('grade_applying', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retain_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_inquiries_guardian_email'), 'admission_inquiries', ['guardian_email'], unique=False)
    op.create_index(op.f('ix_admission_inquiries_id'), 'admission_inquiries', ['id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_admission_inquiries_id'), table_name='admission_inquiries')
    op.drop_index(op.f('ix_admission_inquiries_guardian_email'), table_name='admission_inquiries')
    op.drop_table('admission_inquiries')
    # ### end Alembic commands ###
